[package]
name = "jot"
version = "0.2.0"
authors = ["Olav de Haas <o.n.dehaas@student.tudelft.nl>"]
description = "terminal based digital personal journal📔"

keywords = [ "cli", "terminal", "journal", "notebook", "personal" ]
categories = [ "command-line-utilities" ]

repository = "https://github.com/Olavhaasie/jot"
readme = "README.md"
license = "MIT"

[dependencies]
clap = "2.32"
chrono = "0.4"
sqlite = "0.24"
tempfile = "3"

